home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'personalsite'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('resume', views.ResumeView, name='resume'),
    path('projects', views.ProjectsView, name='projects')

    ]

personalsite/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import IndexView

urlpatterns = [
    path('', include('home.urls', namespace="home")),
    path('admin/', admin.site.urls),
    
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse


def IndexView(request):
    return render(request, 'home/index.html')

def ResumeView(request):
    return render(request, 'home/resume.html')

def ProjectsView(request):
    return render(request,'home/projects.html')
        
    


home/templates/home/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/home_style.css' %}"/>
<link href="https://fonts.googleapis.com/css?family=Niramit|Open+Sans|Oswald|Roboto" rel="stylesheet"/>
<title> Sandy V. Leon - Python Engineer </title>



<header style="color:#4d88ff"> Objective </header>

	<div class="sidebar">
	<div class="portrait"></div>
	<div class ="content-wrapper">
		<p class="sidebar-name"> Sandy V. Leon</p>
		<p class="sidebar-summary" style="padding-left: 16px;"> Python Software Engineer</p>
		<p class="sociallinks" style="color:#1E90FF"> <a href="https://github.com/SandoLando">Github / </a>
		<a href="mailto:sandyvleon@gmail.com"> Email / </a><a href ="https://www.linkedin.com/in/sandy-leon-985b66173/">LinkedIn</a></p>
		
		<ul class="sociallinks">
		<li class="selected">
			<a href="{% url 'home:index' %}">Home</a>
		</li>
		<li class="selected">
			<a href="{% url 'home:resume' %}">Resume</a>
		</li>
		<li class="selected">
			<a href="{% url 'home:projects' %}">Projects</a>
		</li>
		
		
		
			</div>
			
</div>

<div>
<h2 style="padding:30px 0 10px 90px; text-align: center; color:#1E90FF;">
Content Developer Internship — Philadelphia, PA — DataCamp</h2>

<p style="text-align: justify; color: #444; padding: 15px 0 10px 275px; font-size:1.5em; line-height: 1.5em;">I am interested in an intern level position in Python Development. I am highly motivated<br> to learn any skill that will make me better at programming with Python. I am ready and<br> willing
to put in the hours and effort needed to become a skilled developer. My goal is to<br> become a skilled machine learning software engineer.
</p>
</p>
</div>

home/templates/home/projects.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/home_style.css' %}"/>
<link href="https://fonts.googleapis.com/css?family=Niramit|Open+Sans|Oswald|Roboto" rel="stylesheet"/>
<title> Sandy V. Leon - Python Engineer </title>



<header style="color:#4d88ff"> Projects </header>

	<div class="sidebar">
	<div class="portrait"></div>
	<div class ="content-wrapper">
		<p class="sidebar-name"> Sandy V. Leon</p>
		<p class="sidebar-summary" style="padding-left: 16px;"> Python Software Engineer</p>
		<p class="sociallinks" style="color:#1E90FF"> <a href="https://github.com/SandoLando">Github / </a>
		<a href="mailto:sandyvleon@gmail.com"> Email / </a><a href ="https://www.linkedin.com/in/sandy-leon-985b66173/">LinkedIn</a></p>
		
		<ul class="sociallinks">
		
		<li class="selected">
			<a href="{% url 'home:index' %}">Home</a>
		</li>
		
		<li class="selected">
			<a href="{% url 'home:resume' %}">Resume</a>
		</li>
		
		<li class="selected">
			<a href="{% url 'home:projects' %}">Projects</a>
		</li>
		
		
		
			</div>
			
</div>

home/templates/home/resume.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/resume_style.css' %}"/>
<link href="https://fonts.googleapis.com/css?family=Niramit|Open+Sans|Oswald|Roboto" rel="stylesheet"/>
<title> Sandy V. Leon - Python Engineer </title>



<header style="color:#4d88ff"> Resume </header>

	<div class="sidebar">
	<div class="portrait"></div>
	<div class ="content-wrapper">
		<p class="sidebar-name"> Sandy V. Leon</p>
		<p class="sidebar-summary" style="padding-left: 16px;"> Python Software Engineer</p>
		<p class="sociallinks" style="color:#1E90FF"> <a href="https://github.com/SandoLando">Github / </a>
		<a href="mailto:sandyvleon@gmail.com"> Email / </a><a href ="https://www.linkedin.com/in/sandy-leon-985b66173/">LinkedIn</a></p>
		
		<ul class="sociallinks">
		<li class="selected">
			<a href="{% url 'home:index' %}">Home</a>
		</li>
		<li class="selected">
			<a href="{% url 'home:resume' %}">Resume</a>
		</li>
		<li class="selected">
			<a href="{% url 'home:projects' %}">Projects</a>
		</li>
		
			</div>
			
</div>

<div>
<h2 style="padding:30px 0 0 250px; text-align: left; color:#2F4F4F;text-decoration:underline;">
Experience: </h2>
<h3 style="text-align: left;padding-left:250px;color:#2F4F4F;font-weight:500;">Jan2018 - Present&emsp; &emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;Rideshare Driver—Philadephia, PA—Independent Contracter<h3>

<p style="text-align: justify; color: #2F4F4F; padding: 10px 0 10px 515px; font-size:1em; line-height: 1.5em;font-weight:300;">Accommodating passengers and addressing any complaints or concerns<br> that they may have on the way. Ensuring a safe and comfortable trip. I site this work<br> because of the level of communication that is needed to get passengers happily to their<br> destination, a skill that I did not possess at the start of working.</p>

<h2 style="padding:10px 0 0 250px; text-align: left; color:#2F4F4F;text-decoration:underline;">
Education: </h2>
<h3 style="text-align: left;padding-left:250px;color:#2F4F4F;font-weight:500;">Sept2013 - Dec2017&emsp;&emsp;&emsp;&emsp;&emsp;Community College of Philadelphia — Philadephia, PA — Associate in Science</h3>

<h3 style="text-align: left;padding-left:248px;color:#2F4F4F;font-weight:500;">Aug2018 - Present&emsp; &emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;Temple University — Philadephia, PA — Bachelor of Arts in Natural Science<h3>

<h2 style="padding:30px 0 0 250px; text-align: left; color:#2F4F4F;text-decoration:underline;">
Skills: </h2>
<p style="text-align: justify; color: #2F4F4F; padding: 0 0 10px 510px; font-size:1.2em; line-height:1.5em; font-weight:500;"><span style="font-weight:600">Languages:</span>&emsp;English&nbsp;(Fluent)<br>
<span style="padding-left:118px">Spanish&nbsp;(Fluent)</span><br><br>

<span style="font-weight:600">Programming Languages:</span>&emsp;Python<span style="padding-left:22px">(Intermediate)</span><br>
<span style="padding-left:239px">HTML<span style="padding-left:30px">(Basic)<br></span></span>
<span style="padding-left:239px">CSS<span style="padding-left:47px">(Basic)</span></span><br><br>

<span style="font-weight:600">Frameworks/PaaS:</span>&emsp;Django Framework<br>
<span style="padding-left:182px">Heroku cloud platform</span>
</p>




</div>